spring.application.name=java23_production_ready_spring_boot
management.endpoints.web.exposure.include=*
# trace,debug,info,warning,error,off
logging.level.org.springframework=debug
# for production it's prod
spring.profiles.active=prod