spring.application.name=currency-conversion
spring.config.import=optional:configserver:http://localhost:8888
server.address=0.0.0.0
eureka.client.service-url.defaultZone=http://localhost:8000/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost