syntax = "proto3";

import "google/protobuf/timestamp.proto";

message User {
    int32 id = 1;
    string name = 2;
    double salary = 3;
    repeated Department departments = 4;
    
    map<string, string> address_map = 5;
    bool is_active = 6;
    bytes profile_picture = 7;
    google.protobuf.Timestamp join_date = 8;
}

message Department {
    int32 id = 1;
    string name = 2;
}

message UserList {
    repeated User users = 1;
}

message Empty {}

service UserService {
    rpc GetUser(User) returns (User);

    rpc AddUser(User) returns (User);

    rpc GetAllUser(Empty) returns (UserList);
}