spring.application.name=project2_stock_trading_server_using_g_rpc
server.port=8001
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://localhost:5432/project2_stock_trading_server_using_grpc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
grpc.server.reflection-service-enabled=true
grpc.server.port=9090
grpc.server.security.enabled=false
