spring.application.name=java16_spring_data_rest
spring.datasource.url=jdbc:postgresql://localhost:5432/java16_spring_data_rest
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.address=0.0.0.0
server.port=8000