spring.application.name=microservice
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_microservice_1
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
server.port=8000
server.address=0.0.0.0