spring.application.name=java20_spring_jwt_using_nimbus_jose
server.address=0.0.0.0
server.port=8000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/java20_jwt
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create
springdoc.swagger-ui.enabled=true
debug=false
SECRET_STRING=${SECRET_STRING}
JWT_HEADER="Authorization"
