spring.application.name=java20_spring_jwt_using_nimbus_jose_asymmetric
server.address=0.0.0.0
server.port=8000
springdoc.swagger-ui.enabled=true
# spring.security.user.name=user
# spring.security.user.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/java20_jwt 
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update