syntax="proto3";

package com.java22_spring_g_rpc;

import "module_01/test_01.proto";
import "google/protobuf/wrappers.proto"; // for wrapper
import "google/protobuf/timestamp.proto";
option java_multiple_files=true;
option java_package="com.java22_spring_g_rpc";
option java_outer_classname="IntroOuterClass";

enum BodyStyle{
  UNKNOW=0;
  SEDAN=1;
  COUPE=2;
  SUV=3;
}

message Address{
  string street=1;
  string city=2;
  string state=3;
}


message Student{
  string name=1;
  Address address=2;
}

message School{
  int32 id=1;
  string name=2;
  Address address=3;
}


message Book{
  string title=1;
  string author=2;
  int32 publication_year=3;
}



message Library{
  string name=1;
  repeated Book books=2; // array
}


message Car{
  string vendor=1;
  string model=2;
  int32 year=3;
  BodyStyle bodyStyle=4;
}


message CarDealer{
  map<int32,Car> inventory=1; // map
}


message Email{
  string address=1;
  string password=2;
}

message Phone{
  int32 number=1;
  int32 code=2;
}

message Credentials{ // either email or phone
  oneof credential{
    Email email = 1;
    Phone phone = 2;
  }
  module_01.Empty empty=3;
}


// wrapper
message Age{
  google.protobuf.Int32Value age=1;
}


message LastUpdated{
  google.protobuf.Timestamp lastUpdated=1;
  string name=2;
}


message AccountNumber{
  int32 account_number=1;
}


message AccountBalance{
  int32 account_number=1;
  int32 balance=2;
}


service BankService{
  rpc GetAccountBalance(AccountNumber) returns(AccountBalance);
}