spring.application.name=java18_spring_security
server.port=8000
server.address=0.0.0.0
server.servlet.session.cookie.same-site=strict
spring.security.user.name=user
spring.security.user.password=password