spring.application.name=currency_exchange
spring.config.import=optional:configserver:http://localhost:8888
# server.port=8000
server.address=0.0.0.0
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
eureka.client.service-url.defaultZone=http://localhost:8000/eureka/
# eureka.instance.prefer-ip-address=true