spring.application.name=java35_spring_actuator
management.endpoints.web.exposure.include=shutdown,loggers,info
management.info.env.enabled=true
info.app.name=eCommerce Backend
info.app.version=1.0.0
info.app.description=Test Spring Application With Actuator, Grafana, RabitMQ
server.shutdown=graceful
management.endpoint.shutdown.access=unrestricted