spring.application.name=java29_spring_pagination
spring.datasource.url=jdbc:postgresql://localhost:5432/java29_spring_pagination
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
server.port=8001
server.address=0.0.0.0

