spring.application.name=quiz_service
server.address=0.0.0.0
server.port=8001
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices_quiz_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create