spring.application.name=java18_spring_security_project
server.address=0.0.0.0
server.port=8000
spring.datasource.url=jdbc:postgresql://localhost:5432/java18_spring_security_project
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.security.user.name=user
spring.security.user.password=1234


server.servlet.session.cookie.same-site=strict